@echo off
echo Starting Politifolio Backend Demo...

echo 1. Running Setup...
python scripts/setup_dev.py

echo 2. Running Logic Demo...
python demo.py

echo 3. Opening Frontend...
start frontend\index.html

echo 4. Starting API Server...
uvicorn api.app:app --reload
